### ISSUE TITLE
Unable to decompress the pre training model

### ISSUE THREAD

**Issue by Baboom-l** [JUGGHM/PENet_ICRA2021#1]
Display file corruption

**Comment by JUGGHM** [comment]
> Display file corruption

Thank you for your interest! Actually you don't need to decompress the pre-trained model. Just load the file via:

`CUDA_VISIBLE_DEVICES="0" python main.py -b 1 -n e --evaluate [some path]/e.pth.tar`

The parameters were saved in a (.pth.tar) file and it had not been compressed.

**Comment by Baboom-l** [comment]
Thank you for your prompt reply
