### ISSUE TITLE
About the training data

### ISSUE THREAD

**Issue by yuqJin** [JUGGHM/PENet_ICRA2021#11]
Thanks for your code!
I have a question about the KITTI raw data. Do I need to download all the raw data? I know that in the monocular depth estimation, generally only a part of it needs to be downloaded. Is there a download list that I can refer to? thanks!

**Comment by JUGGHM** [comment]
Thanks for your interest! Actually not all raw data is used. Fangchang Ma wrote a [script](https://github.com/fangchangma/self-supervised-depth-completion/blob/master/download/rgb_train_downloader.sh) to download the data. The download list is presented in the script.

**Comment by yuqJin** [comment]
Thanks for your reply! And I have another question. How long did you spend on training?

**Comment by JUGGHM** [comment]
You can refer to the question [9](https://github.com/JUGGHM/PENet_ICRA2021/issues/9).

**Comment by yuqJin** [comment]
> You can refer to the question [9](https://github.com/JUGGHM/PENet_ICRA2021/issues/9).

Thanks！
