### ISSUE TITLE
Training with Multiple GPU's

### ISSUE THREAD

**Issue by danishnazir** [JUGGHM/PENet_ICRA2021#13]
Hi,
Thanks for the code, I am using 4 GPU's to train the model and training pass goes well. However when It starts validation i receive an error given below.

```
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 545, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nazir/PENet_ICRA2021/model.py", line 440, in forward
    sparsed_feature3 = self.depth_layer3(sparsed_feature2_plus, geo_s2, geo_s3) # b 64 88 304
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 545, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/nazir/PENet_ICRA2021/basic.py", line 312, in forward
    x = torch.cat((x, g1), 1)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 176 and 160 in dimension 2 at /tmp/pip-req-build-akjifb_7/aten/src/THC/generic/THCTensorMath.cu:71
```
I assume this is due to the multi-gpu training. I see that you have also used 2 GPUs for training, did you see this issue while training? 

Thanks,

**Comment by JUGGHM** [comment]
Thanks for your interest! The error you mentioned didn't occur in my environments.  I don't think it is owned to multi-GPU training as it is reported in your information: the height(dimension 2) of the tensor _sparsed_feature2_ is 176 but that of  _geo_s2_ is 160 so they can't be concatenated in dimension 1. At the validation stage the heights of both tensors should be 176(352/2).  You could check the size of the tensors or provide more information (the command line, changes you have made, etc)

**Comment by danishnazir** [comment]
HI,
Thanks for your fast reply; yes, you were right. It's not related to Multi-GPU training but instead related to incorrect shapes of tensors in the validation set. Regarding the concatenation of RGB branch decoder information to Depth encoder, In the code, I see that you applied the concatenation in four stages [2,4,6,8]. At the same time, you mentioned that you did it in 5 stages in the research paper. I am attaching the code for more context.

                
  ```
sparsed_feature = self.depth_conv_init(torch.cat((d, rgb_depth), dim=1))  
  sparsed_feature1 = self.depth_layer1(sparsed_feature, geo_s1, geo_s2)# b 32 176 608
  sparsed_feature2 = self.depth_layer2(sparsed_feature1, geo_s2, geo_s2) # b 32 176 608
  sparsed_feature2_plus = torch.cat([rgb_feature2_plus, sparsed_feature2], 1)
  sparsed_feature3 = self.depth_layer3(sparsed_feature2_plus, geo_s2, geo_s3) # b 64 88 304
  sparsed_feature4 = self.depth_layer4(sparsed_feature3, geo_s3, geo_s3) # b 64 88 304
  
  sparsed_feature4_plus = torch.cat([rgb_feature4_plus, sparsed_feature4], 1)
  sparsed_feature5 = self.depth_layer5(sparsed_feature4_plus, geo_s3, geo_s4) # b 128 44 152
  sparsed_feature6 = self.depth_layer6(sparsed_feature5, geo_s4, geo_s4) # b 128 44 152
  
  sparsed_feature6_plus = torch.cat([rgb_feature6_plus, sparsed_feature6], 1)
  sparsed_feature7 = self.depth_layer7(sparsed_feature6_plus, geo_s4, geo_s5) # b 256 22 76
  sparsed_feature8 = self.depth_layer8(sparsed_feature7, geo_s5, geo_s5) # b 256 22 76
  
  sparsed_feature8_plus = torch.cat([rgb_feature8_plus, sparsed_feature8], 1)
  sparsed_feature9 = self.depth_layer9(sparsed_feature8_plus, geo_s5, geo_s6) # b 512 11 38
  sparsed_feature10 = self.depth_layer10(sparsed_feature9, geo_s6, geo_s6) # b 512 11 38
          

```

**Comment by JUGGHM** [comment]
Yes, you were right. The model was initially designed to fuse two-branch features at five scales but we didn't realize this error until this work was finished. As it might not seriously influence the final performance we didn't modify this. But for the elegance and correctness of the model, there should be a concatenating operation on _sparsed_feature_ and _rgb_feature0_plus_ .

**Comment by danishnazir** [comment]
Hmm okay, thank you. I can send in the pull request if you would like.
