### ISSUE TITLE
Query Regarding iRMSE calculation.

### ISSUE THREAD

**Issue by danishnazir** [JUGGHM/PENet_ICRA2021#14]
Hello,
Thank you for the great work.  I want to ask one small query regarding the iRMSE calculation. In your code iRMSE is calculated as follows
```
        # convert from meters to km
        inv_output_km = (1e-3 * output[valid_mask])**(-1)
        inv_target_km = (1e-3 * target[valid_mask])**(-1)
        abs_inv_diff = (inv_output_km - inv_target_km).abs()
        irmse = math.sqrt((torch.pow(abs_inv_diff, 2)).mean())`
```
I want to ask two things 

1. In the first two lines according to your comment, you are converting meters to kilometers. Why are you multiplying with 1e-3 and taking the power to the -1? shouldn't it be 1e3?
2. _inv_output_km_ is causing the iRMSE to go Nan. This is because output[valid_mask] is 0 at some entries of the tensor. Is this normal behavior?. I am using the same dataset as yours. Is it expected to decrease in late epochs? I only ran training for 5 epochs and iRMSE and IMAE are going Nan.
 P.S I am training ENet so I am on round 1.

Thanks for helping out.

**Comment by JUGGHM** [comment]
Hi! 
For the first question: it is 1e-3 as we can see _output_ m = (1e-3*_output_) km.
For the second question: it is expected to decrease in late epochs. However under the settings in the paper (or the same environments and command line in readme)  the inverse metrics are not no longer nan after 2 epochs.

**Comment by danishnazir** [comment]
Thanks for the reply, So iRMSE should go down after 2 epochs in your setting?
