### ISSUE TITLE
RuntimeError: CUDA out of memory. 

### ISSUE THREAD

**Issue by yuqJin** [JUGGHM/PENet_ICRA2021#15]
Hello!

I encountered some difficulties while training the mode.  I run it on sigle NVIDIA GTX 2080 GPU,  but an error occurred

RuntimeError: CUDA out of memory. Tried to allocate 38.00 MiB (GPU 0; 7.79 GiB total capacity; 5.85 GiB already allocated; 87.56 MiB free; 136.18 MiB cached)

I think memory should be sufficient, but it only run successfully when the batch size is reduced to 1, and the gradient jitter is very severe. Do you have any advise for this ？ :(

**Comment by JUGGHM** [comment]
Thanks for your interest! A single 8G-memory 1080/2080 is not sufficient for training the model (ENet). We suggest that you might reduce all channel numbers to half and according to our experience there's 20-25 RMSE loss compared to the original model.

**Comment by yuqJin** [comment]
Thank you very much! It worked

**Comment by ZHANGZ1YUE** [comment]
@JUGGHM Hi! Sorry for opening this issue again. I am also experiencing this error on a 3070Ti 8G machine. But I am not trying to train the model, I just want to test inference the model on my own dataset. How can I solve it?

**Comment by ArghyaChatterjee** [comment]
@ZHANGZ1YUE Were you able to solve the issue ? I am having the same problem during inference.

**Comment by ZHANGZ1YUE** [comment]
> @ZHANGZ1YUE Were you able to solve the issue ? I am having the same problem during inference.

@ArghyaChatterjee I don’t specifically remember but I think the issue was simply about gpu memory. The model is big and image is big, and 8G memory was not enough. I tried reduce the image size and should fixed.
