### ISSUE TITLE
the point cloud looks a bit plausible and noisy

### ISSUE THREAD

**Issue by wmj-ustc** [JUGGHM/PENet_ICRA2021#3]
PENet is efficient and the output depth image seems very nice, but the point cloud transformed from the depth inferred by PENet looks plausible and noisy. Is there something wrong with my matlab code used for transformation? Thank you.
[depth2cloud.zip](https://github.com/JUGGHM/PENet_ICRA2021/files/6268823/depth2cloud.zip)

**Comment by JUGGHM** [comment]
Thanks for your interest! I don't think there is anything wrong in your code.
Actually depth results inferred by regular depth completion models inevitably suffers from artifacts when back projected to 3D space. In other words, not all pixels of the completed depth are reliable. One simple way to select reliable pixels is to predict an additional confidence map and remove pixels with low confidence. You may supervise the confidence prediction network with e^-|D_gt-D|. There also exists some more complex solutions like [DenseLiDAR: A Real-Time Pseudo Dense Depth Guided Depth Completion Network. RAL 2021.].

**Comment by JUGGHM** [comment]
And one recent work claiming to address the smearing depth problem [Depth Completion with Twin Surface Extrapolation at Occlusion Boundaries. In CVPR 2021]

**Comment by wmj-ustc** [comment]
> And one recent work claiming to address the smearing depth problem [Depth Completion with Twin Surface Extrapolation at Occlusion Boundaries. In CVPR 2021]

Thanks so much for your prompt reply.
