### ISSUE TITLE
Why did I only modify the network a little and triple the size of. PTH. Tar?

### ISSUE THREAD

**Issue by Jue-Jue-511** [JUGGHM/PENet_ICRA2021#34]
Thank you very much for sharing this great work~
In the process of modifying your network, I found a small problem. I just increased the network parameters from 131762888 to 131763344. Why did the saved .Pth.tar file triple from about 500m to 1.5G

**Comment by JUGGHM** [comment]
Thanks for your interest. We have removed the optimizer records in our uploaded checkpoints. Therefore they are much smaller than the ones you saved.

**Comment by Jue-Jue-511** [comment]
OK, thank you for your reply~
