### ISSUE TITLE
Can cspn++ accelerate during training？

### ISSUE THREAD

**Issue by jikerWRN** [JUGGHM/PENet_ICRA2021#35]
Hi, thanks for your good work!

I found that cspn++ only accelerate in inference, can it accelerate during training?

Thanks!

**Comment by JUGGHM** [comment]
Thanks for your interest! You could also use the accelerated CSPN++ during training, but the cost is more GPU memory (especially for the dilated CSPN++).

**Comment by jikerWRN** [comment]
Ok, thanks!
