### ISSUE TITLE
Do intesity of pixels of RGB images get normalized to the range [0, 1]?

### ISSUE THREAD

**Issue by quan-dao** [JUGGHM/PENet_ICRA2021#43]
Hello,
Thank you very much for such an amazing work.
I have a question about input of ENet. As I understand from method `__getitem__` of class `KittiDepth`, images represented by variable `rgb` do not get normalized to have pixel intensity in the range [0, 1.0], instead the intesity range is [0, 255]. Is it correct?
Looking forward to your answer.

**Comment by JUGGHM** [comment]
> Hello, Thank you very much for such an amazing work. I have a question about input of ENet. As I understand from method `__getitem__` of class `KittiDepth`, images represented by variable `rgb` do not get normalized to have pixel intensity in the range [0, 1.0], instead the intesity range is [0, 255]. Is it correct? Looking forward to your answer.

Thanks for your interest! And yes you are right.
