### ISSUE TITLE
Normalization Input Data

### ISSUE THREAD

**Issue by MarSpit** [JUGGHM/PENet_ICRA2021#44]
Hi and thank you very much for your great repo. 
As it was mentioned in #43 before, you did not normalize the input data. However, as far as I know it is common practice to do so for a more efficient training and keeping weights and biases small. May I ask why you decided to not normalize your data?

**Comment by JUGGHM** [comment]
Thanks for your interest MarSpit! Actually in this work we just follow the pre-processing pipeline of [FangChang Ma's work](https://github.com/fangchangma/self-supervised-depth-completion)  and it is not a serious decision. And we have not tested yet whether a pre-normalization step will influence the final performance of trained models.

**Comment by MarSpit** [comment]
Okay, I see. Many thanks for your quick answer.
