### ISSUE TITLE
Projection result confirmation

### ISSUE THREAD

**Issue by Orbis36** [JUGGHM/PENet_ICRA2021#49]
Hello,

I'm now working on the cross-modality detection tasks in 3D space. 
Since the SFDNet uses this method as their depth completion way, so I try this repo as well.
The following is the output of PENet and the outcome I obtained when I project them back.
Does it look correct?
I know that the recovered 3d position from the depth map is suffering from the artifacts as u discuss in this issue: https://github.com/JUGGHM/PENet_ICRA2021/issues/3.
But it looks more severe far beyond my expectation.
Thanks for any help

![0000000000](https://user-images.githubusercontent.com/43498946/167985736-83766a95-36b2-4a1e-8a81-c7992877200f.png)
![Screenshot from 2022-05-11 23-01-29](https://user-images.githubusercontent.com/43498946/167985639-ca6a744a-1fa0-43eb-b67c-ded99b61086f.png)
![Screenshot from 2022-05-11 23-00-21](https://user-images.githubusercontent.com/43498946/167985684-96e904d7-9d0b-43d4-861b-8e943308c038.png)

**Comment by Orbis36** [comment]
I test it on KITTI 3D Object detection dataset

**Comment by Orbis36** [comment]
I have found where is the problem, so basically u need to specify the path to .tar file, instead of just the folder name.
I'm stupid

**Comment by san9569** [comment]
Hi, Can you tell me how to solve it in detail?

When I project the depth map, the results is as follows.

![image](https://user-images.githubusercontent.com/60248657/229448776-4eb3558d-0e78-48d2-9888-43e630e38af3.png)

I've specified the weight path correctly.

Thank you in advance !
