### ISSUE TITLE
the difference intrinsic parameters between train and test

### ISSUE THREAD

**Issue by q5390498** [JUGGHM/PENet_ICRA2021#58]
Thank you for your great works. I found the kitti dataset has different intrinsic parameters in train set and test set. But in the test mode, it looks like only use train set carema intrinsic parameters, is there any problem? And can the method works on untrained cameras well? Thank you very much.

**Comment by JUGGHM** [comment]
> Thank you for your great works. I found the kitti dataset has different intrinsic parameters in train set and test set. But in the test mode, it looks like only use train set carema intrinsic parameters, is there any problem? And can the method works on untrained cameras well? Thank you very much.

Thanks for your interest! (1) We found the intrinsic parameter might have not been properly quoted for different sequences(subsets). However it still worked (though incrementally). We didn't carry on further experiments with justified intrinsic parameters. (2) As far as we know, the robustness of the released weights is not very good and are likely to perform poorly on untrained cameras. Re-training is recommended currently. However, I have scheduled to solve these issues in the next work. (But not soon....)

**Comment by q5390498** [comment]
@JUGGHM Thank you for your reply. Is there any recommend papers or docs that can generlize to untrained camera? I hope it can be generalize to the same cameras but have different intinsic parameter and extrinsic parameter and untrained. Thanks!!

**Comment by JUGGHM** [comment]
> @JUGGHM Thank you for your reply. Is there any recommend papers or docs that can generlize to untrained camera? I hope it can be generalize to the same cameras but have different intinsic parameter and extrinsic parameter and untrained. Thanks!!

The problem of lacking generalization should be tackled by training on larger amount of data with more advanced data augmentation strategies. Hereby we recommend doctor [Wei Yin's work](https://arxiv.org/abs/2207.14466).

**Comment by q5390498** [comment]
> > @JUGGHM Thank you for your reply. Is there any recommend papers or docs that can generlize to untrained camera? I hope it can be generalize to the same cameras but have different intinsic parameter and extrinsic parameter and untrained. Thanks!!
> 
> The problem of lacking generalization should be tackled by training on larger amount of data with more advanced data augmentation strategies. Hereby we recommend doctor [Wei Yin's work](https://arxiv.org/abs/2207.14466).

Thank you very much.
