### ISSUE TITLE
Modify DA-CSPN++ for single branch input

### ISSUE THREAD

**Issue by ruinianxu** [JUGGHM/PENet_ICRA2021#59]
Hi JUGGHM,

This is a great work and thank you for open-sourcing the code. I am currently working on modifying DA-CSPN++ for single branch (i.e., remove the second depth dominant branch) but get stuck. [Here](https://github.com/JUGGHM/PENet_ICRA2021/blob/ee4318aaa82f72aa39fa97770196b167722e9515/model.py#L916), guide3 is the downsampled weight but when [computing cspn](https://github.com/JUGGHM/PENet_ICRA2021/blob/ee4318aaa82f72aa39fa97770196b167722e9515/model.py#L979), depth3 and depth are full resolution. I probably miss some parts. Could you give me some insights how this works? 

Thanks

**Comment by JUGGHM** [comment]
> 

Thank you for your interest xu! But I'm afraid that it is of the original resolution, not down-sampled.
