### ISSUE TITLE
Inquiry on the dataset download

### ISSUE THREAD

**Issue by yuanziii** [JUGGHM/PENet_ICRA2021#6]
Hi thanks for your impressive work! My future research interests is on the depth completion so I would like to start with your work!

Just one minor question on downloading the kitti raw data: should I download the rectified or uncertified data? And Are all the branches (road, campus, city, person) are used?

Thanks again for your great work and looking forward to your reply!

**Comment by JUGGHM** [comment]
Thanks for your interest! We use rectified data and all the branches are used. Fangchang Ma wrote a [script](https://github.com/fangchangma/self-supervised-depth-completion/blob/master/download/rgb_train_downloader.sh) to download the data.

**Comment by yuanziii** [comment]
Hi thanks for your nice and quick reply! I will close the issue
